image: python:3.10-slim

stages:
  - test

before_script:
  - apt-get update && apt-get -y install sudo make curl git
  - make prepare-dev

test:
  stage: test
  script:
    - make test

lint:
  stage: test
  script:
    - make lint
